name: Deploy Ticket System

on:
  push:
    branches:
      - master

jobs:
  deploy_to_server1:
    name: Deploy to Server 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          log-public-key: true

      - name: Add SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan "${{ secrets.SERVER1_HOST }}" >> ~/.ssh/known_hosts
          ssh-keyscan "${{ secrets.SERVER2_HOST }}" >> ~/.ssh/known_hosts

      - name: Test SSH Connection to Server 1
        run: |
          ssh -v -o StrictHostKeyChecking=no \
              "${{ secrets.SERVER1_USER }}@${{ secrets.SERVER1_HOST }}" \
              "echo 'SSH to Server 1 successful!'"

#      - name: Upload via SCP to Server 1
#        uses: appleboy/scp-action@v0.0.5
#        with:
#          host: ${{ secrets.SERVER1_HOST }}
#          username: ${{ secrets.SERVER1_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SSH_PORT || 22 }}
#          target: /var/www/smilesrus/ticket
#          source: ./
#          rm: false
#          excludes: "public uploads"  # 排除这两个目录
#          overwrite: true
#          strip_components: 1

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Deploy via rsync to Server 1
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SERVER1_USER }}@${{ secrets.SERVER1_HOST }}:/var/www/smilesrus/ticket

      - name: Fix Permissions
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER1_USER }}@${{ secrets.SERVER1_HOST }} << 'EOF'
          # Fix ownership
          sudo chown -R www-data:www-data /var/www/smilesrus/ticket-public
          
          # Ensure directories exist
          sudo mkdir -p /var/www/smilesrus/ticket-public/assets/{qrcodes,tickets}
          
          # Set permissions
          sudo find /var/www/smilesrus/ticket-public -type d -exec chmod 775 {} \;
          sudo find /var/www/smilesrus/ticket-public -type f -exec chmod 664 {} \;
          sudo chmod -R g+w /var/www/smilesrus/ticket-public/assets
          
          # Set ACLs for persistent permissions
          sudo setfacl -R -d -m u:www-data:rwX /var/www/smilesrus/ticket-public
          EOF

  deploy_to_server2:
    name: Deploy to Server 2
    runs-on: ubuntu-latest
    needs: deploy_to_server1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan "${{ secrets.SERVER2_HOST }}" >> ~/.ssh/known_hosts

      - name: Test SSH Connection to Server 2
        run: |
          ssh -v -o StrictHostKeyChecking=no \
              "${{ secrets.SERVER2_USER }}@${{ secrets.SERVER2_HOST }}" \
              "echo 'SSH to Server 2 successful!'"

#      - name: Upload via SCP to Server 2
#        uses: appleboy/scp-action@v0.0.5
#        with:
#          host: ${{ secrets.SERVER2_HOST }}
#          username: ${{ secrets.SERVER2_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SSH_PORT || 22 }}
#          target: /var/www/tenglong/ticket
#          source: ./
#          rm: false
#          excludes: "public uploads"  # 排除这两个目录
#          overwrite: true
#          timeout: 2m  # 增加超时时间
#          strip_components: 1

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Deploy via rsync to Server 2
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SERVER2_USER }}@${{ secrets.SERVER2_HOST }}:/var/www/tenglong/ticket
      
      - name: Fix Permissions
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER2_USER }}@${{ secrets.SERVER2_HOST }} << 'EOF'
          # Fix ownership
          sudo chown -R www-data:www-data /var/www/tenglong/ticket-public
          
          # Ensure directories exist
          sudo mkdir -p /var/www/tenglong/ticket-public/assets/{qrcodes,tickets}
          
          # Set permissions
          sudo find /var/www/tenglong/ticket-public -type d -exec chmod 775 {} \;
          sudo find /var/www/tenglong/ticket-public -type f -exec chmod 664 {} \;
          sudo chmod -R g+w /var/www/tenglong/ticket-public/assets
          
          # Set ACLs for persistent permissions
          sudo setfacl -R -d -m u:www-data:rwX /var/www/tenglong/ticket-public
          EOF
